# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: OGU0YzdiNzA5ZTNjZTkwNDY1MWM3NTAyOGIyMzQxODI4MTFiNTgwNzk2MmNjMzFjNTgwNDFmNTQyMDQzYTBlNzlhMjIzOGZiNjc2MmEyNGNjYTIwZmFiMzk5NjNlOTcxOTZlZjc4ZWQwNGFiZGQ4NGYxMjAxMWM5ZTBjYjllYmM=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
